[package]
authors = ["Raphael O. <raphael.ob@protonmail.com>"]
name = "panic_handler"
version = "0.1.0"
description = "Set panicking behaviour to halt"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
